// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjrqmiaizfhnhidtsdum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqcnFtaWFpemZobmhpZHRzZHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODc3MDksImV4cCI6MjA2MjA2MzcwOX0.iQRMlGv4EwvAI8o4MY04kqBsJbqfO9W1k0wOl2HUyhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);